import React, { useEffect } from 'react';
import './lessons.css';
import AccessibilityToolbar from './AccessibilityToolbar';

function AiComposedMelodies() {
    useEffect(() => {
        // Add the 'body-lesson' class to body on mount
        document.body.classList.add('body-lesson');
    
        // Clean up by removing the class on unmount
        return () => {
          document.body.classList.remove('body-lesson');
        };
    }, []);

    return (
        <>
            <div className="lesson-container">
                <h1>AI Composed Melodies for Enhanced Musical Creativity</h1>
                <p>AI is transforming how melodies are composed, enabling people of all abilities to engage in music creation. By automating parts of the composition process, AI makes music more accessible, especially for those who may face barriers to traditional music-making due to physical or cognitive limitations.</p>
                
                <h2>Algorithmic Foundations of AI Music Composition</h2>
                <p>AI systems compose music using algorithms like LSTM (Long Short-Term Memory) and Transformer neural networks. These technologies are forms of recurrent neural networks suited to sequence prediction problems:
                    <ul>
                        <li><strong>LSTM Networks:</strong> These are particularly good at capturing time-series data and can remember long input sequences, which is essential for melody generation. They predict the next note in a sequence by learning from vast amounts of existing musical data, understanding both short-term and long-term musical patterns.</li>
                        <li><strong>Transformer Networks:</strong> Originally designed for natural language processing, transformers are adapted for music by treating music composition as a language translation problem—translating feelings or artistic intent into musical notes. They excel in handling sequences with complex relationships and dependencies over longer distances than LSTMs can manage effectively.</li>
                    </ul>
                </p>
                
                <h2>Accessibility in AI-Driven Music Composition</h2>
                <p>AI-generated music tools are designed to be user-friendly, allowing individuals with varying levels of physical mobility and cognitive ability to create complex compositions. These tools often include:
                    <ul>
                        <li><strong>Customizable Interfaces:</strong> Adaptable user interfaces that can be tailored to individual needs, including voice-activated features, single-switch access for users with limited mobility, and simplified control schemes for those with cognitive impairments.</li>
                        <li><strong>Creative Assistance:</strong> AI can suggest melodies based on user input, reducing the need for extensive musical training and allowing users to focus more on creative expression rather than technical skills.</li>
                    </ul>
                </p>
                
                <h2>Example</h2>
                <p>This example demonstrates how users can input basic musical ideas, and the AI helps elaborate these into full compositions:</p>
                <div className="code-example">
                    <pre><code>Input: {"{ root: 'C', pattern: 'ascending', length: 4, style: 'jazz' }"}</code></pre>
                </div>
                <p>Output:</p>
                <div className="output-placeholder">
                    <p>Here, WaveSurfer will visualize the melody generated by AI, which elaborates the simple input into a rich jazz melody.</p>
                </div>

                <h2>Conclusion</h2>
                <p>Through sophisticated algorithms, AI is democratizing music composition, enabling individuals with diverse abilities to participate in and innovate within the musical arts. This technology not only expands creative possibilities but also opens up new avenues for personal expression and enjoyment.</p>
            </div>
            <AccessibilityToolbar />
        </>
    );
}

export default AiComposedMelodies;
